"""
Data package for La Abadia del Crimen.

Contains auto-generated game data (blocks, rooms).
These files are generated by the codegen package.
"""

from .blocks import BLOCK_DEFINITIONS, BlockDef, SubroutineDef, SUBROUTINE_DEFINITIONS
from .rooms import ROOM_DEFINITIONS, RoomDefinition, BlockEntry

__all__ = [
    'BLOCK_DEFINITIONS', 'BlockDef', 'SubroutineDef', 'SUBROUTINE_DEFINITIONS',
    'ROOM_DEFINITIONS', 'RoomDefinition', 'BlockEntry',
]
